name: WalhallaEvents
version: 0.6.0-SNAPSHOT
main: walhalla.mmo.events.WalhallaEventsPlugin
api-version: "1.21"
depend: [WalhallaCore]

commands:
  event:
    description: Manage server events
    usage: /event [list|start <id>|info <id>]
    permission: walhalla.events.use
    permission-message: You don't have permission to use this command
