name: WalhallaZones
version: 0.6.0-SNAPSHOT
main: walhalla.mmo.zones.WalhallaZonesPlugin
api-version: "1.21"
depend: [WalhallaCore]

commands:
  whzones:
    description: WalhallaZones admin commands (OP only)
    usage: /whzones <reload|where>

permissions:
  walhalla.admin.zones:
    description: Allows zone reload/inspect
    default: op
