name: WalhallaMenu
version: 0.6.0-SNAPSHOT
main: walhalla.mmo.menu.WalhallaMenuPlugin
api-version: "1.21"
depend: [WalhallaCore]
softdepend: [WalhallaSpells]

commands:
  menu:
    description: Open the main WalhallaMMO hub menu
    usage: /menu
