name: WalhallaCore
version: 0.6.0-SNAPSHOT
main: walhalla.mmo.core.ValhallaCorePlugin
api-version: "1.21"
commands:
  walhalla:
    description: "Walhalla admin commands (OP only)"
    usage: "/walhalla"
    permission: walhalla.admin
  daily:
    description: "Claim daily rewards"
    usage: "/daily [status]"
permissions:
  walhalla.admin:
    description: "Walhalla admin permission"
    default: op
